name: go - build - pull request

on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/**/go/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.19', '1.20', '1.21.x' ]

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Setup Go ${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install dependencies
      working-directory: src/server/api/go/reminders-api
      run: |
        go env
        go mod download

    - name: Build
      working-directory: src/server/api/go/reminders-api
      run: go build -v ./cmd/app/

    - name: Test with the Go CLI
      working-directory: src/server/api/go/reminders-api
      run: go test ./...
